using DbManager.Parser;
using System;


namespace DbManager
{
    public class ColumnDefinition
    {
        public enum DataType { String, Int, Double}

        public DataType Type;
        public string Name { get; private set; }


        public ColumnDefinition(DataType type, string name) // Aitana
        {
            //TODO DEADLINE 1.A: Initialize member variables
            Type = type;
            Name = name;

        }

        private const string Delimiter = "->";
        private const string DelimiterEncoded = "[ARROW]";

        private static string Encode(string value) // Unai
        {
            //TODO DEADLINE 1.C: Encode the delimiter in the value
            if (string.IsNullOrEmpty(value)) return value;

            return value.Replace(Delimiter, DelimiterEncoded);
            
        }

        private static string Decode(string value) // Unai
        {
            //TODO DEADLINE 1.C: Decode the delimiter in the value
            if (string.IsNullOrEmpty(value)) return value;
            
            return value.Replace(DelimiterEncoded, Delimiter);
            
        }

        public string AsText() // Endika
        {
            //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
            
            return Encode(Name) + Delimiter + Type;
            
        }

        public static ColumnDefinition Parse(string value) // Endika
        {
            //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
            if (string.IsNullOrEmpty(value)) return null;

            string[] parts = value.Split(Delimiter, 2);

            if (parts.Length != 2) return null;

            if (!Enum.TryParse<DataType>(parts[1], out var type)) return null;

            return new ColumnDefinition(type, Decode(parts[0]));
        }
    }
}
